In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# **Data Analysis**

In [48]:
iris_data_set=pd.read_csv("/content/Iris.csv")

In [49]:
iris_data_set.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [50]:
iris_data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [51]:
iris_data_set.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [52]:
iris_data_set.shape

(150, 6)

In [53]:
iris_data_set.head(5)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [54]:
iris_data_set.drop(columns=["Id"],inplace = True)

In [55]:
iris_data_set.head(5)

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [56]:
iris_data_set.tail(5)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

In [57]:
iris_data_set["Species"][80]

'Iris-versicolor'

In [58]:
iris_data_set.loc[90]

SepalLengthCm                5.5
SepalWidthCm                 2.6
PetalLengthCm                4.4
PetalWidthCm                 1.2
Species          Iris-versicolor
Name: 90, dtype: object

In [59]:
iris_data_set.sample(5)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
125            7.2           3.2            6.0           1.8  Iris-virginica
127            6.1           3.0            4.9           1.8  Iris-virginica
35             5.0           3.2            1.2           0.2     Iris-setosa
137            6.4           3.1            5.5           1.8  Iris-virginica
41             4.5           2.3            1.3           0.3     Iris-setosa

In [60]:
species_group = iris_data_set.groupby("Species")

In [61]:
species_group.describe()

                SepalLengthCm                                              \
                        count   mean       std  min    25%  50%  75%  max
Species
Iris-setosa              50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
Iris-versicolor          50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
Iris-virginica           50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

                SepalWidthCm         ... PetalLengthCm      PetalWidthCm  \
                       count   mean  ...           75%  max        count
Species                              ...
Iris-setosa             50.0  3.418  ...         1.575  1.9         50.0
Iris-versicolor         50.0  2.770  ...         4.600  5.1         50.0
Iris-virginica          50.0  2.974  ...         5.875  6.9         50.0


                  mean       std  min  25%  50%  75%  max
Species
Iris-setosa      0.244  0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   2.026  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 32 columns]